name: vibecodingexpert
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
